{{- if .Values.aidboxSecrets.enabled }}
{{- $store := .Values.global.secretStore }}
{{- $prefix := .Values.global.secretStore.remoteKeyPrefix | default "" }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: aidbox-admin-env
  labels:
    app.kubernetes.io/part-of: payerbox
spec:
  refreshInterval: {{ .Values.aidboxSecrets.refreshInterval }}
  secretStoreRef:
    kind: {{ $store.kind }}
    name: {{ $store.name }}
  target:
    name: aidbox-admin-env
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    {{- range $secretKey, $remoteKey := .Values.aidboxSecrets.admin }}
    - secretKey: {{ $secretKey }}
      remoteRef:
        key: {{ printf "%s%s" $prefix $remoteKey | quote }}
    {{- end }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: aidbox-sandbox-env
  labels:
    app.kubernetes.io/part-of: payerbox
spec:
  refreshInterval: {{ .Values.aidboxSecrets.refreshInterval }}
  secretStoreRef:
    kind: {{ $store.kind }}
    name: {{ $store.name }}
  target:
    name: aidbox-sandbox-env
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    {{- range $secretKey, $remoteKey := .Values.aidboxSecrets.sandbox }}
    - secretKey: {{ $secretKey }}
      remoteRef:
        key: {{ printf "%s%s" $prefix $remoteKey | quote }}
    {{- end }}
{{- end }}
