apiVersion: v2
name: prior-auth
description: Smartbox ePA Prior-Authorization service (Da Vinci PAS)
type: application
version: 0.1.0
appVersion: "2605"
home: https://www.health-samurai.io
maintainers:
  - name: Health Samurai
