# =============================================================================
# Aidbox Sandbox - HelmRepository and HelmRelease
# =============================================================================
# This deploys Aidbox via Flux HelmRelease.
# If not using Flux, see README for manual Helm installation.
# =============================================================================
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: aidbox
spec:
  interval: 24h
  url: https://aidbox.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: aidbox
spec:
  interval: 1h
  timeout: 5m
  chart:
    spec:
      chart: aidbox
      sourceRef:
        kind: HelmRepository
        name: aidbox
      interval: 1h
  releaseName: aidbox
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    # =========================================================================
    # Domain Configuration
    # =========================================================================
    # IMPORTANT: Replace with your actual domain
    host: aidbox-sandbox.yourdomain.com
    protocol: https

    # =========================================================================
    # Image Configuration
    # =========================================================================
    image:
      tag: "2510"

    # =========================================================================
    # Aidbox Configuration
    # =========================================================================
    config:
      # Instance identification
      BOX_ID: aidbox-sandbox
      BOX_INSTANCE_NAME: aidbox-sandbox
      BOX_WEB_PORT: 8080

      # Database configuration
      BOX_DB_HOST: aidboxdb.aidbox-db.svc.cluster.local
      BOX_DB_PORT: 5432
      BOX_DB_DATABASE: sandbox

      # Init bundle (bootstrap configuration)
      BOX_INIT_BUNDLE: file:///init-bundle/init-bundle.json

      # FHIR configuration
      BOX_BOOTSTRAP_FHIR_PACKAGES: 'hl7.fhir.r4.core#4.0.1'
      BOX_COMPATIBILITY_VALIDATION_JSON__SCHEMA_REGEX: '#{:fhir-datetime}'
      BOX_FHIR_BUNDLE_EXECUTION_VALIDATION_MODE: limited
      BOX_FHIR_COMPLIANT_MODE: true
      BOX_FHIR_CORRECT_AIDBOX_FORMAT: true
      BOX_FHIR_CREATEDAT_URL: https://aidbox.app/ex/createdAt
      BOX_FHIR_SCHEMA_VALIDATION: true
      BOX_FHIR_SEARCH_AUTHORIZE_INLINE_REQUESTS: false
      BOX_FHIR_SEARCH_CHAIN_SUBSELECT: true
      BOX_FHIR_SEARCH_COMPARISONS: true
      BOX_FHIR_LEGACY_FCE_PACKAGE: us-core-extensions.legacy.aidbox#0.0.0

      # Security configuration
      BOX_MODULE_SDC_STRICT_ACCESS_CONTROL: true
      BOX_SEARCH_INCLUDE_CONFORMANT: true
      BOX_SECURITY_AUDIT_LOG_ENABLED: true
      BOX_SECURITY_DEV_MODE: false
      BOX_SETTINGS_MODE: read-write
      BOX_SECURITY_ORGBAC_ENABLED: true
      BOX_USAGE_STATS: false

      # Observability
      BOX_OBSERVABILITY_STDOUT_PRETTY_LOG_LEVEL: info
      BOX_METRICS_PORT: 8765

    # =========================================================================
    # Secrets Configuration
    # =========================================================================
    # aidbox-secrets: AIDBOX_LICENSE, BOX_AUTH_KEYS_SECRET, BOX_ADMIN_PASSWORD
    # postgres-secrets: BOX_DB_USER, BOX_DB_PASSWORD
    extraEnvFromSecrets:
      - aidbox-secrets
      - postgres-secrets

    # =========================================================================
    # Init Bundle Volume Mount
    # =========================================================================
    volumes:
      - name: init-bundle
        configMap:
          name: init-bundle

    volumeMounts:
      - name: init-bundle
        mountPath: /init-bundle

    # =========================================================================
    # Ingress Configuration
    # =========================================================================
    ingress:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        nginx.ingress.kubernetes.io/ssl-redirect: "true"

    # =========================================================================
    # Resource Limits
    # =========================================================================
    resources:
      limits:
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 2Gi

    # =========================================================================
    # Probes Configuration
    # =========================================================================
    startupProbe:
      initialDelaySeconds: 50
      periodSeconds: 10
      failureThreshold: 20

    # =========================================================================
    # Monitoring
    # =========================================================================
    serviceMonitor:
      enabled: false
