apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.fullname" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
type: Opaque
data:
  {{- with .Values.env }}
  POSTGRES_PASSWORD: {{ .POSTGRES_PASSWORD | b64enc }}
  POSTGRES_USER: {{ .POSTGRES_USER | b64enc }}
  {{- end }}
