apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "postgres.fullname" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  persistentVolumeClaimRetentionPolicy:
    {{- with .Values.persistentVolumeClaimRetentionPolicy }}
    whenDeleted: {{ .whenDeleted }}
    whenScaled: {{ .whenScaled }}
    {{- end }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "postgres.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "postgres.fullname" . }}
  template:
    metadata:
      annotations:
        checksum/config: {{ toJson .Values.config | sha256sum }}
        checksum/env: {{ toJson .Values.env | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "postgres.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        {{- if .Values.walg.enabled }}
        - command:
            - cp
            - /usr/bin/wal-g
            - /binary/wal-g
          image: healthsamurai/wal-g:{{ .Values.walg.image.tag }}
          name: wal-g
          volumeMounts:
            - mountPath: /binary
              name: empty-dir
              subPath: wal-g
        {{- end }}
      containers:
        - args:
            - --config_file=/etc/config/postgres.conf
          envFrom:
            - configMapRef:
                name: {{ include "postgres.fullname" . }}-env
            - secretRef:
                name: {{ include "postgres.fullname" . }}
            {{- range .Values.extraEnvFromSecrets }}
            - secretRef:
                name: {{ . }}
            {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          name: {{ .Chart.Name }}
          ports:
            - name: postgres
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - mountPath: /etc/config
              name: config
            - mountPath: /tmp
              name: empty-dir
              subPath: tmp-dir
            - mountPath: /dev/shm
              name: dshm
            - mountPath: {{ .Values.dataVolumeMountPath }}
              name: data
            {{- if .Values.walg.enabled }}
            - mountPath: /usr/local/sbin
              name: empty-dir
              subPath: wal-g
            {{- end }}
            {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "postgres.serviceAccountName" . }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - configMap:
            name: {{ include "postgres.fullname" . }}-config
            defaultMode: 420
          name: config
        - emptyDir: {}
          name: empty-dir
        - emptyDir:
            medium: Memory
          name: dshm
        {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: {{ required "missing <storage.size> value" .Values.storage.size }}
      {{- if .Values.storage.className }}
      storageClassName: {{ .Values.storage.className }}
      {{- end }}
