apiVersion: v2
name: interop
description: Smartbox ePA Interop service (CMS-0057 patient- & provider-access FHIR APIs)
type: application
version: 0.1.0
appVersion: "2605"
home: https://www.health-samurai.io
maintainers:
  - name: Health Samurai
